<a href="https://colab.research.google.com/github/notShyam7/comment_toxicity/blob/main/CommentToxicity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [2]:
# colab mount
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/


In [3]:
df_test = pd.read_csv('/content/gdrive/MyDrive/Comment Toxicity/test.csv')
df_test_labels = pd.read_csv('/content/gdrive/MyDrive/Comment Toxicity/test_labels.csv')
df_train = pd.read_csv('/content/gdrive/MyDrive/Comment Toxicity/train.csv')

In [4]:
df_train.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [5]:
df_test.head()

id                                       comment_text
0  00001cee341fdb12  Yo bitch Ja Rule is more succesful then you'll...
1  0000247867823ef7  == From RfC == \n\n The title is fine as it is...
2  00013b17ad220c46  " \n\n == Sources == \n\n * Zawe Ashton on Lap...
3  00017563c3f7919a  :If you have a look back at the source, the in...
4  00017695ad8997eb          I don't anonymously edit articles at all.

In [6]:
df_test_labels.head()

id  toxic  severe_toxic  obscene  threat  insult  \
0  00001cee341fdb12     -1            -1       -1      -1      -1   
1  0000247867823ef7     -1            -1       -1      -1      -1   
2  00013b17ad220c46     -1            -1       -1      -1      -1   
3  00017563c3f7919a     -1            -1       -1      -1      -1   
4  00017695ad8997eb     -1            -1       -1      -1      -1   

   identity_hate  
0             -1  
1             -1  
2             -1  
3             -1  
4             -1

In [7]:
df_train.iloc[0]['comment_text']

"Explanation\nWhy the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27"

In [8]:
df_train[df_train.columns[2:]].iloc[0]

toxic            0
severe_toxic     0
obscene          0
threat           0
insult           0
identity_hate    0
Name: 0, dtype: int64

In [9]:
from tensorflow.keras.layers import TextVectorization

In [10]:
#training data
X_train = df_train['comment_text']
y_train = df_train[df_train.columns[2:]].values

In [11]:
#testing data
X_test = df_test['comment_text']
y_test = df_test_labels[df_test_labels.columns[1:]].values

In [12]:
X_train

0         Explanation\nWhy the edits made under my usern...
1         D'aww! He matches this background colour I'm s...
2         Hey man, I'm really not trying to edit war. It...
3         "\nMore\nI can't make any real suggestions on ...
4         You, sir, are my hero. Any chance you remember...
                                ...                        
159566    ":::::And for the second time of asking, when ...
159567    You should be ashamed of yourself \n\nThat is ...
159568    Spitzer \n\nUmm, theres no actual article for ...
159569    And it looks like it was actually you who put ...
159570    "\nAnd ... I really don't think you understand...
Name: comment_text, Length: 159571, dtype: object

In [13]:
y_train

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [14]:
X_test

0         Yo bitch Ja Rule is more succesful then you'll...
1         == From RfC == \n\n The title is fine as it is...
2         " \n\n == Sources == \n\n * Zawe Ashton on Lap...
3         :If you have a look back at the source, the in...
4                 I don't anonymously edit articles at all.
                                ...                        
153159    . \n i totally agree, this stuff is nothing bu...
153160    == Throw from out field to home plate. == \n\n...
153161    " \n\n == Okinotorishima categories == \n\n I ...
153162    " \n\n == ""One of the founding nations of the...
153163    " \n :::Stop already. Your bullshit is not wel...
Name: comment_text, Length: 153164, dtype: object

In [15]:
y_test

array([[-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1],
       ...,
       [-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1]])

In [16]:
MAX_WORDS = 200000 #size of the vocabulary

In [17]:
vectorizer = TextVectorization(max_tokens= MAX_WORDS,
                                            output_sequence_length= 1800,
                                            output_mode= 'int')

In [18]:
vectorizer.adapt(X_train.values)

In [19]:
vectorizer.adapt(X_test.values)

In [ ]:
vectorizer.get_vocabulary()

In [21]:
vectorizer('hello, how are you?')[:4]

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([326,  75,  19,   7])>

In [22]:
vectorized_training_text = vectorizer(X_train.values)

In [23]:
vectorized_testing_text = vectorizer(X_test.values)

In [24]:
vectorized_training_text

<tf.Tensor: shape=(159571, 1800), dtype=int64, numpy=
array([[  738,    80,     2, ...,     0,     0,     0],
       [    1,    55,  3267, ...,     0,     0,     0],
       [  480,   352,    64, ...,     0,     0,     0],
       ...,
       [27758,  6733,   335, ...,     0,     0,     0],
       [    6,    12,   465, ...,     0,     0,     0],
       [    6,     9,   120, ...,     0,     0,     0]])>

In [25]:
training_dataset = tf.data.Dataset.from_tensor_slices((vectorized_training_text, y_train))
training_dataset = training_dataset.cache()
training_dataset = training_dataset.shuffle(160000)
training_dataset = training_dataset.batch(16)
training_dataset = training_dataset.prefetch(8)

In [26]:
testing_dataset = tf.data.Dataset.from_tensor_slices((vectorized_testing_text, y_test))
testing_dataset = testing_dataset.cache()
testing_dataset = testing_dataset.shuffle(160000)
testing_dataset = testing_dataset.batch(16)
testing_dataset = testing_dataset.prefetch(8)

In [27]:
training_dataset.as_numpy_iterator().next()

(array([[   1,  326,  131, ...,    0,    0,    0],
        [1428, 5790,  227, ...,    0,    0,    0],
        [3743,  764,   43, ...,    0,    0,    0],
        ...,
        [ 248,   14,  517, ...,    0,    0,    0],
        [1057,  372,    9, ...,    0,    0,    0],
        [  44,    7, 1577, ...,    0,    0,    0]]),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 1, 1, 0, 1, 0]]))

In [28]:
batch_X_train, batch_y_train = training_dataset.as_numpy_iterator().next()

In [29]:
batch_X_test, batch_y_test = testing_dataset.as_numpy_iterator().next()

In [30]:
batch_X_train.shape

(16, 1800)

In [31]:
batch_y_train.shape

(16, 6)

In [32]:
train = training_dataset.take(int(len(training_dataset)*.7))
val = training_dataset.skip(int(len(training_dataset)*.7)).take(int(len(training_dataset)*.3))
test = testing_dataset.take(int(len(testing_dataset)))

In [33]:
len(train)

6981

In [34]:
train_generator = train.as_numpy_iterator()

In [35]:
train_generator.next()

(array([[  830,   142,   606, ...,     0,     0,     0],
        [    2,   166,    20, ...,     0,     0,     0],
        [    9,   142,   426, ...,     0,     0,     0],
        ...,
        [ 1166,    37,    55, ...,     0,     0,     0],
        [ 2984,    10,     9, ...,     0,     0,     0],
        [ 3220,  2399, 36635, ...,     0,     0,     0]]),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 1, 1, 0, 1, 1],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]))

###Deep Neural Network

In [36]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Bidirectional, Dense, Embedding

In [37]:
from keras.api._v2.keras import activations
model = Sequential()
#creating embedding layer
model.add(Embedding(MAX_WORDS+1, 32))
#creating lstm layer
model.add(Bidirectional(LSTM(32, activation= 'tanh')))
#feature extractor dense layers
model.add(Dense(128, activation= 'relu'))
model.add(Dense(256, activation= 'relu'))
model.add(Dense(128, activation= 'relu'))
#final layer
model.add(Dense(6, activation= 'sigmoid')) #no. of layers

In [38]:
model.compile(loss= 'BinaryCrossentropy', optimizer= 'Adam')

In [39]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 32)          6400032   
                                                                 
 bidirectional (Bidirectiona  (None, 64)               16640     
 l)                                                              
                                                                 
 dense (Dense)               (None, 128)               8320      
                                                                 
 dense_1 (Dense)             (None, 256)               33024     
                                                                 
 dense_2 (Dense)             (None, 128)               32896     
                                                                 
 dense_3 (Dense)             (None, 6)                 774       
                                                        

In [41]:
history = model.fit(train, epochs= 1, validation_data= val)

6981/6981 [==============================] - 800s 115ms/step - loss: 0.0587 - val_loss: 0.0478


In [44]:
history.history

In [45]:
from matplotlib import pyplot as plt

In [ ]:
# plt.figure(figsize=(8,5))
# pd.DataFrame(model.history).plot()
# plt.show()

In [47]:
input_text = vectorizer('im coming for you')

In [48]:
input_text

<tf.Tensor: shape=(1800,), dtype=int64, numpy=array([ 64, 909,  14, ...,   0,   0,   0])>

In [49]:
batch = test.as_numpy_iterator().next()

In [50]:
batch_X_test, batch_y_test = test.as_numpy_iterator().next()

In [51]:
(model.predict(batch_X_test) > 0.5).astype(int)

1/1 [==============================] - 1s 821ms/step


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [52]:
batch_y_test

array([[-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0],
       [-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0],
       [-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0],
       [-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1]])

In [53]:
res = model.predict(batch_X_test)

1/1 [==============================] - 0s 63ms/step


In [54]:
res.flatten()

array([2.3583297e-03, 8.7874135e-08, 8.0664839e-05, 1.5758263e-06,
       1.8211185e-04, 2.5226840e-05, 9.4744610e-04, 1.1798821e-08,
       2.2710699e-05, 3.2155833e-07, 5.5292854e-05, 8.7596845e-06,
       4.6632127e-04, 2.0432460e-09, 8.0232185e-06, 7.2865504e-08,
       2.1317081e-05, 2.6046303e-06, 7.3959399e-03, 1.4359917e-06,
       4.2521421e-04, 1.5945543e-05, 8.4941235e-04, 1.5265374e-04,
       6.3107774e-02, 7.0055779e-05, 5.8219135e-03, 3.6999150e-04,
       1.1752141e-02, 1.7891166e-03, 1.8546813e-03, 5.3230494e-08,
       5.7434409e-05, 1.0675583e-06, 1.3218522e-04, 2.0768606e-05,
       2.7768970e-03, 1.2943418e-07, 1.0115097e-04, 2.1729452e-06,
       2.2534865e-04, 3.2862645e-05, 3.0818608e-01, 1.7980523e-03,
       5.5005230e-02, 5.2519338e-03, 8.6259559e-02, 1.7057985e-02,
       6.2161845e-01, 7.4096676e-03, 1.8057330e-01, 1.1238291e-02,
       2.4066758e-01, 4.1493572e-02, 9.7670060e-01, 1.7568329e-01,
       7.9960829e-01, 4.0300306e-02, 5.9774476e-01, 1.3938525e

In [55]:
from tensorflow.keras.metrics import  Precision, Recall, CategoricalAccuracy

In [56]:
pre = Precision()
re = Recall()
acc = CategoricalAccuracy()

In [57]:
test.as_numpy_iterator().next()

(array([[   440, 161214,    825, ...,      0,      0,      0],
        [  5169,   3588,      1, ...,      0,      0,      0],
        [   282,     43,    282, ...,      0,      0,      0],
        ...,
        [  3149,   4258,    292, ...,      0,      0,      0],
        [   651,    351,     76, ...,      0,      0,      0],
        [    75,   1097,      8, ...,      0,      0,      0]]),
 array([[-1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1],
        [ 0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0],
        [-1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1],
        [ 0,  0,  0,  0,  0,  0],
        [-1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1],
        [ 0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0],
        [-1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1]]))

In [ ]:
for batch in test.as_numpy_iterator():
    # Unpack the batch
    X_true, y_true = batch
    # Make a prediction
    yhat = model.predict(X_true)

    # Flatten the predictions
    y_true = y_true.flatten()
    yhat = yhat.flatten()

    pre.update_state(y_true, yhat)
    re.update_state(y_true, yhat)
    acc.update_state(y_true, yhat)

In [59]:
print(f'Precision: {pre.result().numpy()}, Recall:{re.result().numpy()}, Accuracy:{acc.result().numpy()}')

Precision: 0.9077683687210083, Recall:0.09820528328418732, Accuracy:0.14708033204078674


In [ ]:
!pip install gradio jinja2

In [62]:
import tensorflow as tf
import gradio as gr

In [63]:
model.save('/content/gdrive/MyDrive/Comment Toxicity/toxicity.h5')

In [64]:
model = tf.keras.models.load_model('/content/gdrive/MyDrive/Comment Toxicity/toxicity.h5')

In [65]:
input_str = vectorizer('hey i freaken hate you!')

In [66]:
res = model.predict(np.expand_dims(input_str,0))

1/1 [==============================] - 1s 731ms/step


In [67]:
res

array([[0.64281976, 0.01398416, 0.22558989, 0.01881948, 0.27689037,
        0.06067269]], dtype=float32)

In [71]:
def score_comment(comment):
    vectorized_comment = vectorizer([comment])
    results = model.predict(vectorized_comment)

    text = ''
    for idx, col in enumerate(df_train.columns[2:]):
        text += '{}: {}\n'.format(col, results[0][idx]>0.5)

    return text

In [72]:
interface = gr.Interface(fn=score_comment,
                         inputs=gr.inputs.Textbox(lines=2, placeholder='Comment to score'),
                        outputs='text')

<ipython-input-72-af0826c81d09>:2: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  inputs=gr.inputs.Textbox(lines=2, placeholder='Comment to score'),
<ipython-input-72-af0826c81d09>:2: GradioDeprecationWarning: `optional` parameter is deprecated, and it has no effect
  inputs=gr.inputs.Textbox(lines=2, placeholder='Comment to score'),
<ipython-input-72-af0826c81d09>:2: GradioDeprecationWarning: `numeric` parameter is deprecated, and it has no effect
  inputs=gr.inputs.Textbox(lines=2, placeholder='Comment to score'),


In [73]:
interface.launch(share=True)

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Running on public URL: https://0baef7834cd6a23b55.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
